### ISSUE TITLE
How can i install and use it!

### ISSUE THREAD

**Issue by panmerge** [yangboz/LotteryPrediction#1]
Also some of the featuring links does not work. I think a tutorial is definitely  required for non-programer guys in order to use it, since it seems to be a very interesting and promising  project. Also very educative about running ANN for starters!

**Comment by yangboz** [comment]
@panmerge sorry for poor documention, the  ANN source code is written by AS3,see:https://github.com/yangboz/godpaper/blob/master/TheKnightErrant/src/com/lookbackon/AI/ANN/NeuralNetWork.as

**Comment by yangboz** [comment]
@panmerge the part of Python used Pandas tools,please check: http://pandas.pydata.org/

**Comment by 1085164753** [comment]
You still haven't explain how to use it.
People want to use your software.
Indeed, it is a good project, don't waste it !

**Comment by yangboz** [comment]
@panmerge currenly I am working on DeepLearning4J version...

**Comment by 1085164753** [comment]
Using JVM won't be slow ?
Comparing to C++,
JVM is too slow to do so

**Comment by 1085164753** [comment]
@panmerge Using JVM won't be slow ?
Comparing to C++,
JVM is too slow to do so

**Comment by panmerge** [comment]
@yangboz It's ok to me  don't bother. It isn't solved for me but ok. I wish you good luck for your new projects. Sorry about others' complains it s because your project is indeed interesting.

**Comment by panmerge** [comment]
@1085164753  i know nothing about JVM so i can't answer ... i'm not a developer

**Comment by ulise111** [comment]
How do you install it on Ubuntu?

**Comment by yehoan** [comment]
sir  how  to  open  to use  your  software

**Comment by yangboz** [comment]
@all, move to here[https://github.com/yangboz/LotteryPrediction/wiki#how-can-i-install-and-use-it](https://github.com/yangboz/LotteryPrediction/wiki#how-can-i-install-and-use-it).
