### ISSUE TITLE
这个项目现在进度如何了？

### ISSUE THREAD

**Issue by YachtSail** [yangboz/LotteryPrediction#2]
这是怎么用的。。。目前有没有什么有意思的数据可以分享的吗？

**Comment by yangboz** [comment]
目前正在做DeepLearning的API实现，接着是做一个实用型的微信小程序，对此你有什么期待吗？

**Comment by YachtSail** [comment]
哇。。。希望可以有复式的推荐，估计押中的概率，押蓝，近期号码回顾什么的。买了好久彩票最头疼的就是蓝球不中了=。=出小程序了一定要通知一下啊哈哈，不知道小程序能不能插广告，带来点收益也是不错的

**Comment by yangboz** [comment]
@YachtSail 我们这的幕后投资人“郑总”说很赞:-D

**Comment by yehoan** [comment]
2年过去了  怎么样？？？ 还在深度学习？

**Comment by yangboz** [comment]
数据已经分享在：https://github.com/yangboz/LotteryPrediction/tree/master/lottery-data 欢迎fork,pull request

**Comment by yehoan** [comment]
不是你这个只有双色球  而且我看结果都是很久很久的把

**Comment by yehoan** [comment]
看来不行啊  你这个么有一个软件 什么的？

**Comment by yangboz** [comment]
等到了AutoGluon,https://autogluon.mxnet.io/tutorials/tabular_prediction/tabular-quickstart.html
接下来需要准备历史数据（33选6，16选1）录入到Train/Test.csv了，有时间帮忙整理近期的双色球数据不？

**Comment by yehoan** [comment]
有没有其他联系方式  近期双色球数据？？？ 怎么个整理法
