### ISSUE TITLE
Does this repo use SAS software?

### ISSUE THREAD

**Issue by allanbowe** [yangboz/LotteryPrediction#3]
Just trying to understand the use of the SAS tag / topic

**Comment by yangboz** [comment]
Sorry, missing implementation, the main idea is using R time series library to do that.

**Comment by allanbowe** [comment]
aah ok - was just trying to understand why it was in the top 3 repos for the SAS tag!

https://github.com/topics/sas

Perhaps the tag should be removed, if there is no SAS here?

**Comment by yangboz** [comment]
Sorry, I am on tight schedule, but SAS codebase is undergoing.
