### ISSUE TITLE
Downloaded the zip file

### ISSUE THREAD

**Issue by Turkishcod** [yangboz/LotteryPrediction#4]
Hi yangboz,
  I just downloaded the zip file from : http://yangboz.github.io/LotteryPredi…

I intend trying it on 49ja  bet9ja.com /tv 

I do believe is going to work ??
You made any feature as in that regards ??
The game has 4 colours .....red, blue and yellow while black is for 49 only 
  0 to 49 numbers changing in 4:25mins 

I await your reply thanks  @yangboz

**Comment by yangboz** [comment]
Hi, prediction is based on time series dataset, did you get the history data from bet9ja.com <http://bet9ja.com/>  ?

And now we turn to time based paid software consulting services if you need.

Best,
Yangbo

**Comment by Turkishcod** [comment]
I need the service

**Comment by james55paul** [comment]
Hi I need the code
