### ISSUE TITLE
Examples - usage

### ISSUE THREAD

**Issue by 007-JB** [yangboz/LotteryPrediction#7]
Can 'kinda' see how to install (although the final line "then (swaggerUI)[http://localhost/docs] with example [lottery-data]" doesn't mean much to me - but what you really need to include is a couple of simple examples (python) - you've got the great graphs and swf files (which don't really open up properly - unless I'm using the wrong app to view..) - all you need to do is copy and paste the line of code you used to create respective graphs (doesn't have to be in each of cmd, python and docker - one/something of these is better than nought / nothing).  I'm not the first to flag issues RE: usage - you closed the previous issue after including a link half way down the page (but right up top - my objective view/opinion) - entitled "how to install and use" - but that link only shows installation - nothing RE: usage (i.e. real life / actual code - requesitng python here for a couple of lines - like someone else said - it's great package but going to pitiful waste in the absence of helpful/useful code examples for a couple of applications - copy and paste - give me python examples PLEASE -and try to expand / clarify/reference for further detail the final line "swagger" RE: installation too - soonest if you can Ta!!!

**Comment by yangboz** [comment]
> Can 'kinda' see how to install (although the final line "then (swaggerUI)[http://localhost/docs] with example [lottery-data]" doesn't mean much to me - but what you really need to include is a couple of simple examples (python) - you've got the great graphs and swf files (which don't really open up properly - unless I'm using the wrong app to view..) - all you need to do is copy and paste the line of code you used to create respective graphs (doesn't have to be in each of cmd, python and docker - one/something of these is better than nought / nothing). I'm not the first to flag issues RE: usage - you closed the previous issue after including a link half way down the page (but right up top - my objective view/opinion) - entitled "how to install and use" - but that link only shows installation - nothing RE: usage (i.e. real life / actual code - requesitng python here for a couple of lines - like someone else said - it's great package but going to pitiful waste in the absence of helpful/useful code examples for a couple of applications - copy and paste - give me python examples PLEASE -and try to expand / clarify/reference for further detail the final line "swagger" RE: installation too - soonest if you can Ta!!!

very thankful for your comments, the source code of python is here, and I did a docker image also to be an workable usage quick example, sorry the poor document for user, should notice the docker env requirements. again, tight work-schedule.

**Comment by yangboz** [comment]
and please the [WiKi](https://github.com/yangboz/LotteryPrediction/wiki) as kinda example.

**Comment by 007-JB** [comment]
Hmmm.. not sure I really follow - you've proivded two lines of explaination that result in me being exaclty where I was beore with a bigger ? mark hanging over this.  Have you seen bogs / descriptions like this before? https://www.displayr.com/installing-r-packages-from-github/  - I think if you humoured my request for 5-10 mins, you'd see that with a great program/package like the one I *believe* you have, your reach would be far greater -this would be to both yourself an wider/community.  Kindly assist.  ta
