### ISSUE TITLE
Issue closed prematurely  - further explaination required - 

### ISSUE THREAD

**Issue by 007-JB** [yangboz/LotteryPrediction#8]
refer to "Examples - usage #7". Please don't take this the wrong way but as far as my question/query was concerned - your soln may have made sense to you but did little for me - this I classify this issue as still being open.

Kindly assist - it's only because I believe you have an awesome package but do not ahve the same techincal detail / knowledge as yourself (given you are theone you created thsi for starters).  I do not see any remedy -

Trust you will find the short time requireed to exaplain your resoonse o=in furhter datail ta

**Comment by yangboz** [comment]
@007-JB thanks for your big interesting , now I am tight schedule to develop a dart version on  it. hopefully  this version will be more full document on examples and coding self-explanation-able.
stay tuned.

**Comment by 007-JB** [comment]
ta

**Comment by 007-JB** [comment]
Ok sorry if I was a bit rough / didn't put this the right way I honestly didn't mean anything by it in a negative way /hurtful way - hope we're good best wishes!

**Comment by yangboz** [comment]
any way , thanks.
