### ISSUE TITLE
Lottery prediction 

### ISSUE THREAD

**Issue by sath1412** [yangboz/LotteryPrediction#9]
Hi, good morning sir. I need to find out 1st prize lottery result. Could you please help me to make it possible

**Comment by yangboz** [comment]
please explain more with  game rule and historic-data.

**Comment by sath1412** [comment]
Hi, Good morning brother. This is satheesh. Thanks for your response. This
is my WhatsApp number+918903617327.please do message me in this number. We
will find out the probability of getting three digit winning numbers.
